version: "3"
services:

  service:
    build: .
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/ping"]
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - 8080:8080
