// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package container

import (
	"github.com/jedi4z/minesweeper-api/app/repositories/mysql_repositories"
	"github.com/jedi4z/minesweeper-api/app/usecases"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitializeContainer(db *gorm.DB) Container {
	gameRepositoryInterface := mysql_repositories.NewGameRepository(db)
	gameUseCasesInterface := usecases.NewGameUseCases(gameRepositoryInterface)
	cellRepositoryInterface := mysql_repositories.NewCellRepository(db)
	cellUseCasesInterface := usecases.NewCellUseCases(cellRepositoryInterface)
	container := NewContainer(gameUseCasesInterface, cellUseCasesInterface)
	return container
}
