// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package container

import (
	"github.com/jedi4z/minesweeper-api/app/repositories/mysql_repositories"
	"github.com/jedi4z/minesweeper-api/app/usecases"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitializeContainer(db *gorm.DB) Container {
	userRepositoryInterface := mysql_repositories.NewUserRepository(db)
	userUseCaseInterface := usecases.NewUserUseCase(userRepositoryInterface)
	gameRepositoryInterface := mysql_repositories.NewGameRepository(db)
	gameUseCasesInterface := usecases.NewGameUseCases(gameRepositoryInterface)
	container := NewContainer(userUseCaseInterface, gameUseCasesInterface)
	return container
}
